name = "starc-cm"
compatibility_date = "2026-09-14"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "starc_db"
database_id = "abcf198e-a738-4758-80d9-267be42f476e"

[[kv_namespaces]]
binding = "KV"
id = "555fd1f5c5d34e4d958f3dddb8c5abd0"

[[r2_buckets]]
binding = "FILES"
bucket_name = "starc-files"

[vars]
WHATSAPP_ADMIN = "2376XXXXXXXX"
DEFAULT_SHIPPING_RATE = "2500"
DEFAULT_CUSTOMS_RATE = "32"
