name = "starc-cms"
compatibility_date = "2025-09-19"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build:cf"

[[d1_databases]]
binding = "DB"
database_name = "starc_cms_db"
database_id = "2cc8e844-3ad8-4d58-9606-c4ea2cc285f3"

[[r2_buckets]]
binding = "R2"
bucket_name = "starc-cms-media"

[observability]
enabled = true
